common/urls.py
from django.conf.urls import url, include
from common.views import (
    LoginView, LogoutView, HomePageView, RegisterView, UserDeleteView,
    UserProfileList, UserTicketRecordsView,InchargePageView, DailyReportsView,
    MonthlyReportsView
)

urlpatterns = [

    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', HomePageView.as_view(), name='index'),
    url(r'^incharge/$', InchargePageView.as_view(), name='index2'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(
        r'^userlist/$',
        UserProfileList.as_view(),
        name='list_user'
    ),

    url(
        r'^user/delete/(?P<pk>\d+)/$',
        UserDeleteView.as_view(),
        name='delete_user'
    ),

    url(
        r'^user/(?P<user_id>\d+)/record/$',
        UserTicketRecordsView.as_view(),
        name='user_records'
    ),
    url(
        r'^user/(?P<user_id>\d+)/record/(?P<date>[a-zA-Z0-9_-]+)/$',
        UserTicketRecordsView.as_view(),
        name='user_records_date'
    ),
    url(
        r'^daily/reports/$',
        DailyReportsView.as_view(),
        name='daily_reports'
    ),
    url(
        r'^monthly/reports/$',
        MonthlyReportsView.as_view(),
        name='monthly_reports'
    ),
]

daewoo_staff/urls.py
from django.conf.urls import url, include
from daewoo_staff.views import (
    AddDriver, DriverList, DriverDeleteView, DriverUpdateView, AddEmployee, EmployeeList, EmployeeDeleteView, EmployeeUpdateView,

)

urlpatterns = [
    url(
        r'^add/$',
        AddDriver.as_view(),
        name='add_driver'
    ),

    url(
        r'^list/$',
        DriverList.as_view(),
        name='driver_list'
    ),

    url(
        r'^delete/(?P<pk>\d+)/$',
        DriverDeleteView.as_view(),
        name='driver_delete'
    ),

    url(
        r'^update/(?P<pk>\d+)/$',
        DriverUpdateView.as_view(),
        name='driver_update'
    ),
########################################## Employee YRLS ###################################
    url(
        r'^addemployee/$',
        AddEmployee.as_view(),
        name='add_employee'
    ),

    url(
        r'^listemployee/$',
        EmployeeList.as_view(),
        name='list_employee'
    ),

    url(
        r'^deleteemployee/(?P<pk>\d+)/$',
        EmployeeDeleteView.as_view(),
        name='delete_employee'
    ),

    url(
        r'^updateemployee/(?P<pk>\d+)/$',
        EmployeeUpdateView.as_view(),
        name='update_employee'
    ),
]

daewoo_ticketing_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('common.urls', namespace='common')),
    url(r'^booking/', include('daewoo_booking.urls', namespace='booking')),
    url(r'^vehicle/', include('daewoo_vehicle.urls', namespace='vehicle')),
    url(r'^staff/', include('daewoo_staff.urls', namespace='staff')),
    url(r'^route/', include('daewoo_route.urls', namespace='route')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/staff/add_driver.html
{% extends 'base.html' %}
{%block menu_staff%}active{%endblock%}
{% block submenu_add_driver%}active{%endblock%}
{% block submenu_list_driver%}active{%endblock%}

{% block content %}
    <div class="col-md-6">
        <br>
        <a href="{% url 'staff:driver_list' %}"><button type="button" class="btn btn-primary" style="float: left">All Drivers</button></a>
        <br><br><br>
        <div class="content-panel">
            <h3 class="text-center">New Driver</h3>
            <div class="panel-body">
                <form action="{% url 'staff:add_driver' %}" method="post" class="adddriver" >
                    {% csrf_token %}
                    <label><strong>Name</strong></label>
                    <input type="text" class="form-control" name="name" id="name">
                    <span class="name" style="color: red; display: none" >This Field is Requried</span>
                    <br>
                    <label><strong>Father Name.</strong></label>
                    <input type="text" class="form-control" name="father_name" id="fathername">
                    <span class="fathername" style="color: red; display: none" >This Field is Requried</span>
                    <br>
                    <label><strong>Cnic</strong></label>
                    <input title="text" class="form-control" name="cnic" id="cnic">
                    <span class="cnic" style="color: red; display: none" >This Field is Requried</span>
                    <br>
                    <label><strong>Address</strong></label>
                    <input type="text" class="form-control" name="address" id="address">
                    <span class="address" style="color: red; display: none" >This Field is Requried</span>
                    <br>
                    <label><strong>Mobile</strong></label>
                    <input type="text" class="form-control" name="mobile" id="mobile">
                    <span class="mobile" style="color: red; display: none" >This Field is Requried</span>
                    <br>
                    <label><strong>Joinning Date</strong></label>
                    <input type="date" class="form-control" name="joinning_date" id="date">
                    <span class="date" style="color: red; display: none" >This Field is Requried</span>
                    <br>
                    <label><strong>Salary</strong></label>
                    <input type="text" class="form-control" name="salary" id="salary">
                    <span class="salary" style="color: red; display: none" >This Field is Requried</span>
                    <br>
                     <label><strong>Select Bus</strong></label>
                   <select name="plate_no" class="form-control" id="busplate" required="">
                    <option value="">Bus number</option>
                        {% for bus in daewoo %}
                        <option >{{ bus.plate_no }}</option>
                        {% endfor %}
                   </select>
                    <span class="busplate" style="color: red; display: none" >This Field is Requried</span>
                    <br><br>
                    <input type="button" value="save" class="btn btn-primary right" id="save">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
{{ block.super }}

<script>
 $(document).ready(function(){
 $('#save').on('click', function () {
                var error = false;

                if ($('#name').val() ==""){
                    $('.name').show();
                    error = true;
                }
                else {
                    $('.name').hide();
                }
                if ($('#fathername').val() == ""){
                    $('.fathername').show();
                    error = true;
                }
                else {
                    $('.fathername').hide();
                }
                if ($('#cnic').val() == ""){
                    $('.cnic').show();
                    error = true;
                }
                else {
                    $('.cnic').hide();
                }
                if ($('#mobile').val() == ""){
                    $('.mobile').show();
                    error = true;
                }
                else {
                    $('.mobile').hide();

                }
                if ($('#address').val() == ""){
                    $('.address').show();
                    error = true;
                }
                else {
                    $('.address').hide();

                }
                if ($('#date').val() == ""){
                    $('.date').show();
                    error = true;
                }
                else {
                    $('.date').hide();

                }
                if ($('#salary').val() == ""){
                    $('.salary').show();
                    error = true;
                }
                else {
                    $('.salary').hide();

                }
                if ($('#busplate').val() == ""){
                    $('.busplate').show();
                    error = true;
                }
                else {
                    $('.busplate').hide();

                }
                if (error == false)
                {
                    $('.adddriver').submit();
                }

            });
             $('#mobile').keyup(function () {
                $('.mobile').hide();
                checkDec(this);
            });
            function checkDec(el){
                var ex = /^[0-9]+\.?[0-9]*$/;
                if(ex.test(el.value)==false){
                    el.value = el.value.substring(0,el.value.length - 1);
                }
            }
             $('#cnic').keyup(function () {
                $('.cnic').hide();
                checkDec(this);
            });
            function checkDec(el){
                var ex = /^[0-9]+\.?[0-9]*$/;
                if(ex.test(el.value)==false){
                    el.value = el.value.substring(0,el.value.length - 1);
                }
            }
             $('#salary').keyup(function () {
                $('.salary').hide();
                checkDec(this);
            });
            function checkDec(el){
                var ex = /^[0-9]+\.?[0-9]*$/;
                if(ex.test(el.value)==false){
                    el.value = el.value.substring(0,el.value.length - 1);
                }
            }
            $('#name').keyup(function () {
                $('.name').hide();
            })
             $('#fathername').keyup(function () {
                $('.fathername').hide();
            })
             $('#cnic').keyup(function () {
                $('.cnic').hide();
            })
             $('#address').keyup(function () {
                $('.address').hide();
            })
             $('#mobile').keyup(function () {
                $('.mobile').hide();
            })
             $('#salary').keyup(function () {
                $('.salary').hide();
            })
             $('#date').click(function () {
                $('.date').hide();
            })
             $('#busplate').click(function () {
                $('.busplate').hide();
            })
             })
</script>
{% endblock %}

templates/staff/add_employee.html
{% extends 'base.html' %}
{%block menu_staff%}active{%endblock%}
{% block submenu_add_employee%}active{%endblock%}

{% block content %}
    <div class="col-md-6">
        <br>
        <a href="{% url 'staff:list_employee' %}"><button type="button" class="btn btn-primary" style="float: left">All Employees</button></a>
        <br><br><br>
        <div class="content-panel">
            <h3 class="text-center">New Employee</h3>
            <div class="panel-body">
                <form action="{% url 'staff:add_employee' %}" method="post" class="addemployee" >
                    {% csrf_token %}
                    <label><strong>Designtion</strong></label>
                    <input type="text" class="form-control" name="designation" id="designation">
                    <span class="designation" style="color: red; display: none" >This Field is Requried</span>
                    <br>
                    <label><strong>Name</strong></label>
                    <input type="text" class="form-control" name="name" id="name">
                    <span class="name" style="color: red; display: none" >This Field is Requried</span>
                    <br>
                    <label><strong>Father Name.</strong></label>
                    <input type="text" class="form-control" name="father_name" id="fathername">
                    <span class="fathername" style="color: red; display: none" >This Field is Requried</span>
                    <br>
                    <label><strong>Cnic</strong></label>
                    <input title="text" class="form-control" name="cnic" id="cnic">
                    <span class="cnic" style="color: red; display: none" >This Field is Requried</span>
                    <br>
                    <label><strong>Address.</strong></label>
                    <input type="text" class="form-control" name="address" id="address">
                    <span class="address" style="color: red; display: none" >This Field is Requried</span>
                    <br>
                    <label><strong>mobile</strong></label>
                    <input type="text" class="form-control" name="mobile" id="mobile">
                    <span class="mobile" style="color: red; display: none" >This Field is Requried</span>
                    <br>
                    <label><strong>Joinning Date.</strong></label>
                    <input type="date" class="form-control" name="joinning_date" id="date">
                    <span class="date" style="color: red; display: none" >This Field is Requried</span>
                    <br>
                    <label><strong>Salary.</strong></label>
                    <input type="text" class="form-control" name="salary" id="salary">
                    <span class="salary" style="color: red; display: none" >This Field is Requried</span>
                    <br>
                    <input type="button" value="Save" class="btn btn-primary right" id="save">
                </form>
            </div>
        </div>
    </div>
{% endblock %}


{% block scripts %}
{{ block.super }}

<script>
 $(document).ready(function(){
 $('#save').on('click', function () {
                var error = false;

                if ($('#name').val() ==""){
                    $('.name').show();
                    error = true;
                }
                else {
                    $('.name').hide();
                }
                if ($('#fathername').val() == ""){
                    $('.fathername').show();
                    error = true;
                }
                else {
                    $('.fathername').hide();
                }
                if ($('#cnic').val() == ""){
                    $('.cnic').show();
                    error = true;
                }
                else {
                    $('.cnic').hide();
                }
                if ($('#mobile').val() == ""){
                    $('.mobile').show();
                    error = true;
                }
                else {
                    $('.mobile').hide();

                }
                if ($('#address').val() == ""){
                    $('.address').show();
                    error = true;
                }
                else {
                    $('.address').hide();

                }
                if ($('#date').val() == ""){
                    $('.date').show();
                    error = true;
                }
                else {
                    $('.date').hide();

                }
                if ($('#salary').val() == ""){
                    $('.salary').show();
                    error = true;
                }
                else {
                    $('.salary').hide();

                }
                if ($('#designation').val() == ""){
                    $('.designation').show();
                    error = true;
                }
                else {
                    $('.designation').hide();

                }
                if (error == false)
                {
                    $('.addemployee').submit();
                }

            });
             $('#mobile').keyup(function () {
                $('.mobile').hide();
                checkDec(this);
            });
            function checkDec(el){
                var ex = /^[0-9]+\.?[0-9]*$/;
                if(ex.test(el.value)==false){
                    el.value = el.value.substring(0,el.value.length - 1);
                }
            }
             $('#cnic').keyup(function () {
                $('.cnic').hide();
                checkDec(this);
            });
            function checkDec(el){
                var ex = /^[0-9]+\.?[0-9]*$/;
                if(ex.test(el.value)==false){
                    el.value = el.value.substring(0,el.value.length - 1);
                }
            }
             $('#salary').keyup(function () {
                $('.salary').hide();
                checkDec(this);
            });
            function checkDec(el){
                var ex = /^[0-9]+\.?[0-9]*$/;
                if(ex.test(el.value)==false){
                    el.value = el.value.substring(0,el.value.length - 1);
                }
            }
            $('#name').keyup(function () {
                $('.name').hide();
            })
             $('#fathername').keyup(function () {
                $('.fathername').hide();
            })
             $('#cnic').keyup(function () {
                $('.cnic').hide();
            })
             $('#address').keyup(function () {
                $('.address').hide();
            })
             $('#mobile').keyup(function () {
                $('.mobile').hide();
            })
             $('#salary').keyup(function () {
                $('.salary').hide();
            })
             $('#date').click(function () {
                $('.date').hide();
            })
             $('#designation').keyup(function () {
                $('.designation').hide();
            })
             })
</script>

{% endblock %}

templates/staff/list_driver.html
{% extends 'base.html' %}
{%block menu_staff%}active{%endblock%}
{% block submenu_list_driver%}active{%endblock%}

{% block content %}
    <!--<div class="container">-->
        <div class="row">
            <div class="col-lg-12">
                <br>
                <a href="{% url 'staff:add_driver' %}"><button type="button" class="btn btn-primary">Add Drivers</button></a>
                <br><br>
                <div class="content-panel table-responsive">
                    <h2 class="text-center">Drivers</h2>
                    <div class="row">
                        <div class="col-lg-5">
                            <div class="input-group custom-search-form col-lg-12" style="left: 5px">
                                <input type="text" class="form-control search-daewoo" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>

                    <hr>
                    <table class="table table-striped table-advance table-hover daewoos-table">
                        <thead>
                        <tr>
                            <th>S.No</th>
                            <th><i class="fa fa-user"></i> Name </th>
                            <th><i class="fa fa-male"></i> Father Name </th>
                            <th><i class="fa fa-info-circle"></i> Cnic </th>
                            <th><i class="fa fa-map-marker"></i> Address </th>
                            <th><i class=" fa fa-mobile"></i> Mobile </th>
                            <th><i class="fa fa-calendar"></i> Joining Date </th>
                            <th><i class="fa fa-money"></i> Salary </th>
                            <th><i class=" fa fa-car"></i> Bus </th>
                            <th><i class=" fa fa-edit"></i> Actions</th>
                        </tr>
                        </thead>
                        <tbody class="daewoos-table-body">
                        {% if not drivers %}
                            <tr><td colspan="6" class="text-center">Record Not Found</td></tr>
                        {% endif %}
                        {% for driver in drivers %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="#">{{ driver.name }}</a></td>
                                <td>{{ driver.father_name }}</td>
                                <td class="#">{{ driver.cnic }}</td>
                                <td>{{ driver.address }}</td>
                                <td>{{ driver.mobile }}</td>
                                <td>{{ driver.joinning_date }}</td>
                                <td>{{ driver.daewoo }}</td>
                                <td>{{ driver.salary }}</td>
                                <td>
                                    <a href="{% url 'staff:driver_update' pk=driver.id %}"><button class="btn btn-primary btn-xs" title="Update "><i class="fa fa-edit"></i></button></a>
                                    <a href="{% url 'staff:driver_delete' pk=driver.id %}"><button class="btn btn-danger btn-xs" title="Delete "><i class="fa fa-trash-o"></i></button></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

{% endblock %}

templates/staff/list_employee.html
{% extends 'base.html' %}
{%block menu_staff%}active{%endblock%}
{% block submenu_list_employee%}active{%endblock%}

{% block content %}
    <!--<div class="container">-->
        <div class="row">
            <div class="col-lg-12">
                <br>
                <a href="{% url 'staff:add_employee' %}"><button type="button" class="btn btn-primary">Add Employee</button></a>
                <br><br>
                <div class="content-panel table-responsive">
                    <h2 class="text-center">Employees</h2>
                    <div class="row">
                        <div class="col-lg-5">
                            <div class="input-group custom-search-form col-lg-12" style="left: 5px">
                                <input type="text" class="form-control search-daewoo" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>

                    <hr>
                    <table class="table table-striped table-advance table-hover daewoos-table">
                        <thead>
                        <tr>
                            <th>S.No</th>
                            <th><i class="fa fa-tasks"></i> Designation </th>
                            <th><i class="fa fa-user"></i> Name </th>
                            <th><i class="fa fa-male"></i> Father Name </th>
                            <th><i class="fa fa-info-circle"></i> Cnic </th>
                            <th><i class="fa fa-map-marker"></i> Address </th>
                            <th><i class="fa fa-mobile"></i> Mobile </th>
                            <th><i class="fa fa-calendar"></i> Joining Date </th>
                            <th><i class="fa fa-money"></i> Salary </th>
                            <th><i class="fa fa-edit"></i>Actions</th>
                        </tr>
                        </thead>
                        <tbody class="daewoos-table-body">
                        {% if not employees %}
                            <tr><td colspan="6" class="text-center">Record Not Found</td></tr>
                        {% endif %}
                        {% for employee in employees %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ employee.designation }}</td>
                                <td><a href="#">{{ employee.name }}</a></td>
                                <td>{{ employee.father_name }}</td>
                                <td class="#">{{ employee.cnic }}</td>
                                <td>{{ employee.address }}</td>
                                <td>{{ employee.mobile }}</td>
                                <td>{{ employee.joinning_date }}</td>
                                <td>{{ employee.salary }}</td>
                                <td>
                                    <a href="{% url 'staff:update_employee' pk=employee.id %}"><button class="btn btn-primary btn-xs" title="Update employee"><i class="fa fa-edit"></i></button></a>
                                    <a href="{% url 'staff:delete_employee' pk=employee.id %}"><button class="btn btn-danger btn-xs" title="Delete employee"><i class="fa fa-trash-o"></i></button></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

{% endblock %}