common/urls.py
from django.conf.urls import url, include
from common.views import (
    LoginView, LogoutView, HomePageView, RegisterView, UserDeleteView,
    UserProfileList, UserTicketRecordsView,InchargePageView, DailyReportsView,
    MonthlyReportsView
)

urlpatterns = [

    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', HomePageView.as_view(), name='index'),
    url(r'^incharge/$', InchargePageView.as_view(), name='index2'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(
        r'^userlist/$',
        UserProfileList.as_view(),
        name='list_user'
    ),

    url(
        r'^user/delete/(?P<pk>\d+)/$',
        UserDeleteView.as_view(),
        name='delete_user'
    ),

    url(
        r'^user/(?P<user_id>\d+)/record/$',
        UserTicketRecordsView.as_view(),
        name='user_records'
    ),
    url(
        r'^user/(?P<user_id>\d+)/record/(?P<date>[a-zA-Z0-9_-]+)/$',
        UserTicketRecordsView.as_view(),
        name='user_records_date'
    ),
    url(
        r'^daily/reports/$',
        DailyReportsView.as_view(),
        name='daily_reports'
    ),
    url(
        r'^monthly/reports/$',
        MonthlyReportsView.as_view(),
        name='monthly_reports'
    ),
]

daewoo_booking/urls.py
from django.conf.urls import url, include
from daewoo_booking.views import (
    CreateSchedule, SeatBooking,  BookingTicket,
    VehicleBookingDetailsForm, VehicleBookingDetails, StationReservationList, AddStationReservation, DeleteStationReservation,
    TicketCancellationFormView, BookingListView, BookingDeleteView, PassengerRecordView, PassengerRecordListView, UpdateStationReservation,
    VehicleBookingCNICDetails, VehicleBookingCNICDetailsForm,
)

from daewoo_booking.api_views import (
    CreateBookingAPIView, MakeBookingPaymentAPIView
)

urlpatterns = [
    url(
        r'^schedule/$',
        CreateSchedule.as_view(),
        name='create_schedule'
    ),
    url(
        r'^seat/destination/(?P<destination_id>\d+)/'
        r'station/(?P<station_id>\d+)/departure'
        r'/(?P<departure_id>\d+)/date/(?P<date>.+)/$',
        SeatBooking.as_view(),
        name='booking_seat'
    ),
    url(
        r'^(?P<booking_id>\d+)/ticket/$',
        BookingTicket.as_view(),
        name='booking_ticket'
    ),

    url(
        r'^vehicle/details/form/$',
        VehicleBookingDetailsForm.as_view(),
        name='vehicle_details_form'
    ),

    url(
        r'^vehicle/cnic/details/form/$',
        VehicleBookingCNICDetailsForm.as_view(),
        name='vehicle_cnic_details_form'
    ),

    url(
        r'^vehicle/destination/(?P<destination_id>\d+)/'
        r'timing/(?P<timing_id>\d+)/date/(?P<date>.+)/details/',
        VehicleBookingDetails.as_view(),
        name='vehicle_details'
    ),
    url(
        r'^vehicle/cnic/destination/(?P<destination_id>\d+)/'
        r'timing/(?P<timing_id>\d+)/date/(?P<date>.+)/details/',
        VehicleBookingCNICDetails.as_view(),
        name='vehicle_cnic_details'
    ),


    url(
        r'^seat/booking/$',
        SeatBooking.as_view(),
        name='seat_booking'
    ),

    url(
        r'^ticket/cancellation/form/$',
        TicketCancellationFormView.as_view(),
        name='ticket_cancellation_form'
    ),

    url(
        r'^destination/(?P<destination_id>\d+)/'
        r'timing/(?P<timing_id>\d+)/date/(?P<date>.+)/list/',
        BookingListView.as_view(),
        name='booking_list'
    ),

    url(
        r'^(?P<pk>\d+)/delete/$',
        BookingDeleteView.as_view(),
        name='delete_booking'
    ),

    url(
        r'^passenger/record/$',
        PassengerRecordView.as_view(),
        name='passenger_record'
    ),

    url(
        r'^passenger/(?P<code>.+)/record/$',
        PassengerRecordListView.as_view(),
        name='passenger_record_result'
    ),

    # Booking API's
    url(
        r'^create/api/$',
        CreateBookingAPIView.as_view(),
        name='create_booking_api'
    ),

    url(
        r'^reservedstations/$',
        StationReservationList.as_view(),
        name='list_reservedstations'
    ),

    url(
        r'^add/reservedstations/$',
        AddStationReservation.as_view(),
        name='add_reservedstations'
    ),

    url(
        r'^delete/reservedstations/(?P<pk>\d+)/$',
        DeleteStationReservation.as_view(),
        name='delete_reservedstations'
    ),

    url(
        r'^update/reservedstations/(?P<pk>\d+)/$',
        UpdateStationReservation.as_view(),
        name='update_reservedstations'
    ),

    url(
        r'^(?P<booking_id>\d+)/payment/api/$',
        MakeBookingPaymentAPIView.as_view(),
        name='make_payment_api'
    )
]

daewoo_route/urls.py
from django.conf.urls import url, include
from daewoo_route.views import (
    AddRoute, RouteList, RouteUpdateView, RouteDeleteView, DestinationList, DestinationUpdateView, AddDestination,
    DestinationDeleteView, AddStation, StationsList, StationDeleteView, StationUpdateView, AddDepartureTiming,
    DepartureTimingList, DepartureTimingUpdateView, DepartureTimingDeleteView,
)

from daewoo_route.api_views import DepartureTimingAPIView, StationsAPIView

urlpatterns = [
    url(
        r'^add/$',
        AddRoute.as_view(),
        name='add_route'
    ),

    url(
        r'^list/$',
        RouteList.as_view(),
        name='list_route'
    ),

    url(
        r'^delete/(?P<pk>\d+)/$',
        RouteDeleteView.as_view(),
        name='delete_route'
    ),

    url(
        r'^update/(?P<pk>\d+)/$',
        RouteUpdateView.as_view(),
        name='update_route'
    ),

    ############################ Destination URLS ##################################

    url(
        r'^adddestination/$',
        AddDestination.as_view(),
        name='add_destination'
    ),

    url(
        r'^listdestination/$',
        DestinationList.as_view(),
        name='list_destination'
    ),

    url(
        r'^deletedestination/(?P<pk>\d+)/$',
        DestinationDeleteView.as_view(),
        name='delete_destination'
    ),

    url(
        r'^updatedestination/(?P<pk>\d+)/$',
        DestinationUpdateView.as_view(),
        name='update_destination'
    ),

    ###########################  Stations URLS ######################################

    url(
        r'^addstaion/$',
        AddStation.as_view(),
        name='add_station'
    ),

    url(
        r'^liststation/$',
        StationsList.as_view(),
        name='list_station'
    ),

    url(
        r'^deletestation/(?P<pk>\d+)/$',
        StationDeleteView.as_view(),
        name='delete_station'
    ),

    url(
        r'^updatestation/(?P<pk>\d+)/$',
        StationUpdateView.as_view(),
        name='update_station'
    ),

    ######################################## Departure Timing Urls #####################################

    url(
        r'^adddeparture/$',
        AddDepartureTiming.as_view(),
        name='add_departure'
    ),

    url(
        r'^listdeparture/$',
        DepartureTimingList.as_view(),
        name='list_departure'
    ),

    url(
        r'^deletedeparture/(?P<pk>\d+)/$',
        DepartureTimingDeleteView.as_view(),
        name='delete_departure'
    ),

    url(
        r'^updatedeparture/(?P<pk>\d+)/$',
        DepartureTimingUpdateView.as_view(),
        name='update_departure'
    ),

    ########################################  Route Timings URLS #######################################
    url(
        r'^departure/timing/api/$',
        DepartureTimingAPIView.as_view(),
        name='departure_timing_api'
    ),

    url(
        r'^stations/api/$',
        StationsAPIView.as_view(),
        name='stations_api'
    ),
]

daewoo_ticketing_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('common.urls', namespace='common')),
    url(r'^booking/', include('daewoo_booking.urls', namespace='booking')),
    url(r'^vehicle/', include('daewoo_vehicle.urls', namespace='vehicle')),
    url(r'^staff/', include('daewoo_staff.urls', namespace='staff')),
    url(r'^route/', include('daewoo_route.urls', namespace='route')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/booking/booking_list.html
{% extends 'base.html' %}
{%block menu_booking%}active{%endblock%}
{% block submenu_reschedule%}active{%endblock%}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <br>
            <a href="{% url 'booking:create_schedule' %}"><button type="button" class="btn btn-primary">New Schedule</button></a>
            <br><br>
            <div class="content-panel table-responsive">
                <h2 class="text-center">Booking List</h2>
                <div class="row">
                    <div class="col-lg-5">
                        <div class="input-group custom-search-form col-lg-12" style="left: 5px">
                            <input type="text" class="form-control search-daewoo" placeholder="Search...">
                            <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4"></div>
                    <div class="col-lg-4"></div>
                    <div class="col-lg-4"></div>
                </div>

                <div style="float: right; padding: 12px;" class="remove-print-display">
                        <strong>Bus Type:</strong> <span style="color: red">{{ departure_timing.daewoo_type }}</span>&nbsp;&nbsp;&nbsp;&nbsp;
                        <strong> Destination:</strong> <span style="color: red">{{ departure_timing.destination.name }}</span>&nbsp;&nbsp;&nbsp;&nbsp;
                        <strong> Timing:</strong> <span style="color: red">{{ departure_timing.timing }}</span>&nbsp;&nbsp;&nbsp;&nbsp;

                    </div>


                <table class="table table-striped table-advance table-hover daewoos-table">
                    <thead>
                    <tr>
                        <th>S.No</th>
                        <th><i class="fa fa-bullhorn"></i> Passenger </th>
                        <th><i class="fa fa-question-circle"></i> CNIC </th>
                        <th><i class=" fa fa-bookmark"></i> Mobile </th>
                        <th><i class=" fa fa-edit"></i> Seats </th>
{#                        <th><i class=" fa fa-edit"></i> Departure </th>#}
                        <th><i class=" fa fa-edit"></i> Total Amount </th>
                        <th><i class=" fa fa-bomb"></i> Payment </th>
                        <th><i class=" fa fa-bomb"></i> Booking Date </th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody class="daewoos-table-body">
                    {% if not booking_list %}
                        <tr><td colspan="6" class="text-center">Record Not Found</td></tr>
                    {% endif %}
                    {% for booking in booking_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td><a href="#">{% if booking.passenger %}{{ booking.passenger.name }}{% else %}{{ booking.station_reservation.name|title }} ({{ booking.station_reservation.station_name|title }}){% endif %}</a></td>
                            <td>{{ booking.passenger.cnic }}</td>
                            <td>{{ booking.passenger.mobile_no }}</td>
                            <td>{{ booking.seats_no }}</td>
                            <td>{{ booking.total_amount|floatformat }}</td>
                            <td>{% if booking.has_payment %}<i class="fa fa-check-circle" style="color: #439D44"></i>{% else %}<a href="{% url 'booking:make_payment_api' booking_id=booking.id %}"><i class="fa fa-times-circle" onclick="return confirm('Are you sure to make payments')" style="color: #C9312C; cursor: pointer" title="Make Payment"></i></a>{% endif %}</td>
                            <td>{{ booking.booking_date }}</td>
                            <td>
                                <a href="{% url 'booking:booking_ticket' booking_id=booking.id %}"><button class="btn btn-success btn-xs" title="View"><i class="fa fa-eye"></i></button></a>
                                <a href="{% url 'booking:delete_booking' pk=booking.id %}"><button onclick="return confirm('Are you sure you want to DELETE Reservation?')" class="btn btn-danger btn-xs" title="Cancellation"><i class="fa fa-trash-o"></i></button></a>

                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
{{ block.super }}

<script>

</script>

{% endblock %}

templates/booking/create_schedule.html
{% extends 'base.html' %}
{%block menu_booking%}active{%endblock%}
{% block submenu_add_booking%}active{%endblock%}
{% block content %}
    <div class="row mt">
        <div class="col-lg-7 col-md-6 col-sm-12 col-lg-offset-1">
            <div class="showback">
                <form  class="booking">
                    <div class="row">
                        <div class="col-md-9 col-md-offset-1">
                            <h3>Get Your Schedule</h3>
                            <div class="form-group">
                                <label>From</label>
                                <select class="form-control">
                                    <option selected>Quetta</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Destination</label>
                                <select class="form-control destination" id="destination">
                                    <option value="">--To--</option>
                                    {% for destination in destinations %}
                                        <option data-id="{{ destination.id }}">{{ destination.name }}</option>
                                    {% endfor %}
                                </select>
                                <span class="destination_error" style="color: red; display: none" >This Field is Requried</span>
                            </div>
                            <div class="form-group">
                                <label>Departure Timing</label>
                                <select class="form-control departure_timing" id="departure_timing">
                                    <option value=""></option>
                                </select>
                                <span class="departure_timing_error" style="color: red; display: none" >This Field is Requried</span>
                            </div>
                            <div class="form-group">
                                <label>Station</label>
                                <select class="form-control station" id="station">
                                    <option value="" ></option>
                                </select>
                                <span class="station_error" style="color: red; display: none" >This Field is Requried</span>
                            </div>
                            <div class="form-group">
                                <label>Booking Date</label>
                                <input type="date" class="form-control departure_date" id="departure_date">
                                <span class="departure_date_error" style="color: red; display: none" >This Field is Requried</span>
                            </div>
                            <input type="button" class="btn btn-primary schedule " id="schedule" value="Get Schedule">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script>
        $(function () {
            $('.destination').on('change', function () {
                $.post(
                    '{% url "route:departure_timing_api" %}',
                    {'destination': $('.destination').val()},
                    function (result, status) {
                        var departure_timing_data = '<option data-id="0">--Timing--</option>';
                        $.each(result.departure_timings, function(key, result){
                            departure_timing_data += '<option data-id="' + result.id + '">' + result.timing + '</option>';
                        });

                        $('#departure_timing').html(departure_timing_data);
                    }
                )
            });
            $('#departure_timing').on('change', function(){
                $.post(
                    '{% url "route:stations_api" %}',
                    {'destination': $('.destination').val(), 'departure_timing': $(this).find(':selected').data('id')},
                    function (result, status) {

                        var station_data = '<option>--Station--</option>';
                        $.each(result.stations, function(key, result){
                            station_data += '<option data-id="' + result.id + '">' + result.station + '</option>';
                        });
                        $('.station').html(station_data);
                    }
                )
            });

            // Need to be used for the redirection

        });

        $('#schedule').on('click', function () {
            var error = false;

            if ($('#destination').val() == ""){
                $('.destination_error').show();
                error = true;
            }
            else {
                $('.destination_error').hide();
            }
            if ($('#station').val() == ""){
                $('.station_error').show();
                error = true;
            }
            else {
                $('.station_error').hide();
            }
            if ($('#departure_timing').val() == ""){
                $('.departure_timing_error').show();
                error = true;
            }
            else {
                $('.departure_timing_error').hide();
            }
            if ($('#departure_date').val() == ""){
                $('.departure_date_error').show();
                error = true;
            }
            else {
                $('.departure_date_error').hide();
            }
            $('#destination').click(function () {
                $('.destination_error').hide();
            });
            $('#departure_date').click(function () {
                $('.departure_date_error').hide();
            });
            $('#departure_timing').click(function () {
                $('.departure_timing_error').hide();
            });
            $('#station').click(function () {
                $('.station_error').hide();
            });
            if (error == false)
            {
                var destination_id = $('.destination').find(':selected').data('id');
                var station_id = $('.station').find(':selected').data('id');
                var timing_id = $('.departure_timing').find(':selected').data('id');
                var departure_date = $('.departure_date').val();
                window.location.href = '/booking/seat/destination/' + destination_id + '/station/' + station_id +  '/departure/' + timing_id + '/date/' + departure_date + '/';
            } else {
                return;
            }

        });

    </script>
{% endblock %}

templates/booking/passenger_booking.html
{% extends 'base.html' %}
{%block menu-passenger_record%}active{%endblock%}
{% block submenu_search_passenger %}active{% endblock %}
{% block content %}
        <div class="row">
            <div class="col-lg-12">
                <br>
                <a href="{% url 'booking:passenger_record' %}"><button type="button" class="btn btn-primary">Search Passenger</button></a>
                <br><br>
                <div class="content-panel table-responsive">
                    <h2 class="text-center">Passenger Booking Detail</h2>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="input-group custom-search-form col-lg-12" style="left: 5px">
                                <input type="text" class="form-control search-daewoo" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>

                    <hr>
                    <table class="table table-striped table-advance table-hover daewoos-table">
                        <thead>
                        <tr>
                            <th>S.No</th>
                            <th><i class="fa fa-bullhorn"></i> Name </th>
                            <th><i class="fa fa-bullhorn"></i> Ticket No </th>
                            <th><i class="fa fa-bullhorn"></i> Station </th>
                            <th><i class="fa fa-bullhorn"></i> Route </th>
                            <th><i class="fa fa-bullhorn"></i> Destination </th>
                            <th><i class="fa fa-bullhorn"></i> Departure </th>
                        </tr>
                        </thead>
                        <tbody class="daewoos-table-body">
                        {% if not bookings %}
                            <tr><td colspan="6" class="text-center">Record Not Found</td></tr>
                        {% endif %}
                        {% for booking in bookings %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="#">{{ booking.passenger.name }}</a></td>
                                <td>{{ booking.seats_no}}</td>
                                <td>{{ booking.station.name}}</td>
                                <td>{{ booking.route.name}}</td>
                                <td>{{ booking.destination.name}}</td>
                                <td>{{ booking.departure}}</td>

                                <td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

{% endblock %}

templates/booking/ticket_cancellation_form.html
{% extends 'base.html' %}
{%block menu_booking%}active{%endblock%}
{% block submenu_reschedule%}active{%endblock%}

{% block content %}

    <div class="row mt">
        <div class="col-lg-7 col-md-6 col-sm-12 col-lg-offset-1">
            <div class="showback">
                <form>
                    <div class="row">
                        <div class="col-md-9 col-md-offset-1">
                            <h3>Get Your Schedule</h3>
                            <div class="form-group">
                                <label>From</label>
                                <select class="form-control">
                                    <option selected>Quetta</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Destination</label>
                                <select class="form-control destination" id="destination">
                                    <option>--To--</option>
                                    {% for destination in destinations %}
                                        <option data-id="{{ destination.id }}">{{ destination.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                            </div>
                            <div class="form-group">
                                <label>Departure Timing</label>
                                <select class="form-control departure_timing" id="departure_timing">
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Booking Date</label>
                                <input type="date" class="form-control departure_date" id="departure_date">
                            </div>
                            <a class="btn btn-primary schedule" id="schedule"  href="#">Get Schedule</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script>
        $(function () {
            $('.destination').on('change', function () {
               $.post(
                   '{% url "route:departure_timing_api" %}',
                   {'destination': $('.destination').val()},
                   function (result, status) {
                       var departure_timing_data = '<option>--Timing--</option>';
                       $.each(result.departure_timings, function(key, result){
                           departure_timing_data += '<option data-id="' + result.id + '">' + result.timing + '</option>';
                       });

                       {#var station_data = '<option>--Station--</option>';#}
                       {#$.each(result.stations, function(key, result){#}
                       {#    station_data += '<option data-id="' + result.id + '">' + result.station + '</option>';#}
                       {#});#}

                       $('#departure_timing').html(departure_timing_data);
                       $('.station').html(station_data);
                   }
               )
            });

            // Need to be used for the redirection


            $('.schedule').on('click', function () {
                var destination_id = $('.destination').find(':selected').data('id');
                var station_id = $('.station').find(':selected').data('id');
                var timing_id = $('.departure_timing').find(':selected').data('id');
                var departure_date = $('.departure_date').val();

                window.location.href = '/booking/destination/' + destination_id + '/timing/' + timing_id +  '/date/' + departure_date + '/list/';

            });

        });
    </script>
{% endblock %}

templates/booking/vehicle_cnic_details_form.html
{% extends 'base.html' %}
{%block menu_booking%}active{%endblock%}
{% block submenu_details_cnic%}active{%endblock%}

{% block content %}

    <div class="row mt">
        <div class="col-lg-7 col-md-6 col-sm-12 col-lg-offset-1">
            <div class="showback">
                <form>
                    <div class="row">
                        <div class="col-md-9 col-md-offset-1">
                            <h3>Get Your Schedule</h3>
                            <div class="form-group">
                                <label>From</label>
                                <select class="form-control">
                                    <option selected>Quetta</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Destination</label>
                                <select class="form-control destination" id="destination">
                                    <option>--To--</option>
                                    {% for destination in destinations %}
                                        <option data-id="{{ destination.id }}">{{ destination.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
{#                            <div class="form-group">#}
{#                                <label>Station</label>#}
{#                                <select class="form-control station" id="station">#}
{#                                </select>#}
{#                            </div>#}
                            <div class="form-group">
                                <label>Departure Timing</label>
                                <select class="form-control departure_timing" id="departure_timing">
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Booking Date</label>
                                <input type="date" class="form-control departure_date" id="departure_date">
                            </div>
                            <a class="btn btn-primary booking-details" id="booking-details"  href="#">Details</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script>
        $(function () {
            $('.destination').on('change', function () {
               $.post(
                   '{% url "route:departure_timing_api" %}',
                   {'destination': $('.destination').val()},
                   function (result, status) {
                       var departure_timing_data = '<option>--Timing--</option>';
                       $.each(result.departure_timings, function(key, result){
                           departure_timing_data += '<option data-id="' + result.id + '">' + result.timing + '</option>';
                       });

{#                       var station_data = '<option>--Station--</option>';#}
{#                       $.each(result.stations, function(key, result){#}
{#                           station_data += '<option data-id="' + result.id + '">' + result.station + '</option>';#}
{#                       });#}

                       $('#departure_timing').html(departure_timing_data);
                       $('.station').html(station_data);
                   }
               )
            });

            // Need to be used for the redirection


            $('.booking-details').on('click', function () {
                var destination_id = $('.destination').find(':selected').data('id');
                var station_id = $('.station').find(':selected').data('id');
                var timing_id = $('.departure_timing').find(':selected').data('id');
                var departure_date = $('.departure_date').val();
                window.location.href = '/booking/vehicle/cnic/destination/' + destination_id + '/timing/' + timing_id +  '/date/' + departure_date + '/details/';

            });

        });
    </script>
{% endblock %}