common/urls.py
from django.conf.urls import url, include
from common.views import (
    LoginView, LogoutView, HomePageView, RegisterView, UserDeleteView,
    UserProfileList, UserTicketRecordsView,InchargePageView, DailyReportsView,
    MonthlyReportsView
)

urlpatterns = [

    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', HomePageView.as_view(), name='index'),
    url(r'^incharge/$', InchargePageView.as_view(), name='index2'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(
        r'^userlist/$',
        UserProfileList.as_view(),
        name='list_user'
    ),

    url(
        r'^user/delete/(?P<pk>\d+)/$',
        UserDeleteView.as_view(),
        name='delete_user'
    ),

    url(
        r'^user/(?P<user_id>\d+)/record/$',
        UserTicketRecordsView.as_view(),
        name='user_records'
    ),
    url(
        r'^user/(?P<user_id>\d+)/record/(?P<date>[a-zA-Z0-9_-]+)/$',
        UserTicketRecordsView.as_view(),
        name='user_records_date'
    ),
    url(
        r'^daily/reports/$',
        DailyReportsView.as_view(),
        name='daily_reports'
    ),
    url(
        r'^monthly/reports/$',
        MonthlyReportsView.as_view(),
        name='monthly_reports'
    ),
]

daewoo_booking/urls.py
from django.conf.urls import url, include
from daewoo_booking.views import (
    CreateSchedule, SeatBooking,  BookingTicket,
    VehicleBookingDetailsForm, VehicleBookingDetails, StationReservationList, AddStationReservation, DeleteStationReservation,
    TicketCancellationFormView, BookingListView, BookingDeleteView, PassengerRecordView, PassengerRecordListView, UpdateStationReservation,
    VehicleBookingCNICDetails, VehicleBookingCNICDetailsForm,
)

from daewoo_booking.api_views import (
    CreateBookingAPIView, MakeBookingPaymentAPIView
)

urlpatterns = [
    url(
        r'^schedule/$',
        CreateSchedule.as_view(),
        name='create_schedule'
    ),
    url(
        r'^seat/destination/(?P<destination_id>\d+)/'
        r'station/(?P<station_id>\d+)/departure'
        r'/(?P<departure_id>\d+)/date/(?P<date>.+)/$',
        SeatBooking.as_view(),
        name='booking_seat'
    ),
    url(
        r'^(?P<booking_id>\d+)/ticket/$',
        BookingTicket.as_view(),
        name='booking_ticket'
    ),

    url(
        r'^vehicle/details/form/$',
        VehicleBookingDetailsForm.as_view(),
        name='vehicle_details_form'
    ),

    url(
        r'^vehicle/cnic/details/form/$',
        VehicleBookingCNICDetailsForm.as_view(),
        name='vehicle_cnic_details_form'
    ),

    url(
        r'^vehicle/destination/(?P<destination_id>\d+)/'
        r'timing/(?P<timing_id>\d+)/date/(?P<date>.+)/details/',
        VehicleBookingDetails.as_view(),
        name='vehicle_details'
    ),
    url(
        r'^vehicle/cnic/destination/(?P<destination_id>\d+)/'
        r'timing/(?P<timing_id>\d+)/date/(?P<date>.+)/details/',
        VehicleBookingCNICDetails.as_view(),
        name='vehicle_cnic_details'
    ),


    url(
        r'^seat/booking/$',
        SeatBooking.as_view(),
        name='seat_booking'
    ),

    url(
        r'^ticket/cancellation/form/$',
        TicketCancellationFormView.as_view(),
        name='ticket_cancellation_form'
    ),

    url(
        r'^destination/(?P<destination_id>\d+)/'
        r'timing/(?P<timing_id>\d+)/date/(?P<date>.+)/list/',
        BookingListView.as_view(),
        name='booking_list'
    ),

    url(
        r'^(?P<pk>\d+)/delete/$',
        BookingDeleteView.as_view(),
        name='delete_booking'
    ),

    url(
        r'^passenger/record/$',
        PassengerRecordView.as_view(),
        name='passenger_record'
    ),

    url(
        r'^passenger/(?P<code>.+)/record/$',
        PassengerRecordListView.as_view(),
        name='passenger_record_result'
    ),

    # Booking API's
    url(
        r'^create/api/$',
        CreateBookingAPIView.as_view(),
        name='create_booking_api'
    ),

    url(
        r'^reservedstations/$',
        StationReservationList.as_view(),
        name='list_reservedstations'
    ),

    url(
        r'^add/reservedstations/$',
        AddStationReservation.as_view(),
        name='add_reservedstations'
    ),

    url(
        r'^delete/reservedstations/(?P<pk>\d+)/$',
        DeleteStationReservation.as_view(),
        name='delete_reservedstations'
    ),

    url(
        r'^update/reservedstations/(?P<pk>\d+)/$',
        UpdateStationReservation.as_view(),
        name='update_reservedstations'
    ),

    url(
        r'^(?P<booking_id>\d+)/payment/api/$',
        MakeBookingPaymentAPIView.as_view(),
        name='make_payment_api'
    )
]

daewoo_route/urls.py
from django.conf.urls import url, include
from daewoo_route.views import (
    AddRoute, RouteList, RouteUpdateView, RouteDeleteView, DestinationList, DestinationUpdateView, AddDestination,
    DestinationDeleteView, AddStation, StationsList, StationDeleteView, StationUpdateView, AddDepartureTiming,
    DepartureTimingList, DepartureTimingUpdateView, DepartureTimingDeleteView,
)

from daewoo_route.api_views import DepartureTimingAPIView, StationsAPIView

urlpatterns = [
    url(
        r'^add/$',
        AddRoute.as_view(),
        name='add_route'
    ),

    url(
        r'^list/$',
        RouteList.as_view(),
        name='list_route'
    ),

    url(
        r'^delete/(?P<pk>\d+)/$',
        RouteDeleteView.as_view(),
        name='delete_route'
    ),

    url(
        r'^update/(?P<pk>\d+)/$',
        RouteUpdateView.as_view(),
        name='update_route'
    ),

    ############################ Destination URLS ##################################

    url(
        r'^adddestination/$',
        AddDestination.as_view(),
        name='add_destination'
    ),

    url(
        r'^listdestination/$',
        DestinationList.as_view(),
        name='list_destination'
    ),

    url(
        r'^deletedestination/(?P<pk>\d+)/$',
        DestinationDeleteView.as_view(),
        name='delete_destination'
    ),

    url(
        r'^updatedestination/(?P<pk>\d+)/$',
        DestinationUpdateView.as_view(),
        name='update_destination'
    ),

    ###########################  Stations URLS ######################################

    url(
        r'^addstaion/$',
        AddStation.as_view(),
        name='add_station'
    ),

    url(
        r'^liststation/$',
        StationsList.as_view(),
        name='list_station'
    ),

    url(
        r'^deletestation/(?P<pk>\d+)/$',
        StationDeleteView.as_view(),
        name='delete_station'
    ),

    url(
        r'^updatestation/(?P<pk>\d+)/$',
        StationUpdateView.as_view(),
        name='update_station'
    ),

    ######################################## Departure Timing Urls #####################################

    url(
        r'^adddeparture/$',
        AddDepartureTiming.as_view(),
        name='add_departure'
    ),

    url(
        r'^listdeparture/$',
        DepartureTimingList.as_view(),
        name='list_departure'
    ),

    url(
        r'^deletedeparture/(?P<pk>\d+)/$',
        DepartureTimingDeleteView.as_view(),
        name='delete_departure'
    ),

    url(
        r'^updatedeparture/(?P<pk>\d+)/$',
        DepartureTimingUpdateView.as_view(),
        name='update_departure'
    ),

    ########################################  Route Timings URLS #######################################
    url(
        r'^departure/timing/api/$',
        DepartureTimingAPIView.as_view(),
        name='departure_timing_api'
    ),

    url(
        r'^stations/api/$',
        StationsAPIView.as_view(),
        name='stations_api'
    ),
]

daewoo_ticketing_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('common.urls', namespace='common')),
    url(r'^booking/', include('daewoo_booking.urls', namespace='booking')),
    url(r'^vehicle/', include('daewoo_vehicle.urls', namespace='vehicle')),
    url(r'^staff/', include('daewoo_staff.urls', namespace='staff')),
    url(r'^route/', include('daewoo_route.urls', namespace='route')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/stations/add_reservedstations.html
{% extends 'base.html' %}
{%block menu_reserved_stations%}active{%endblock%}
{% block submenu_add_reservation%}active{%endblock%}

{% block content %}
    <div class="col-md-6">
        <br>
        <a href="{% url 'booking:list_reservedstations' %}"><button type="button" class="btn btn-primary" style="float: left">All Reserved Stations</button></a>
        <br><br><br>
        <div class="content-panel">
            <h3 class="text-center">New Reserved Stations</h3>
            <div class="panel-body">
                <form action="{% url 'booking:add_reservedstations' %}" method="post" class="addstation" >
                    {% csrf_token %}
                    <br>
                    <label><strong>Name</strong></label>
                    <input type="text" class="form-control" id="name" name="name">
                    <span class="name" style="color: red; display: none" >This Field is Requried</span><br>
                    <label><strong>Mobile No</strong></label>
                    <input title="text" class="form-control daewoo_name" id="mobile_no" name="mobile_no">
                    <span class="fare" style="color: red; display: none" >This Field is Requried</span><br>
                    <label><strong>Station</strong></label>
                    <input type="text" class="form-control" id="station_name" name="station_name">
                    <span class="name" style="color: red; display: none" >This Field is Requried</span><br>


                     <input type="button" id="save" value="Save" class="btn btn-primary right">
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
{{ block.super }}

<script>
 $(document).ready(function(){
 $('#save').on('click', function () {
                var error = false;

                if ($('#name').val() == ""){
                    $('.name').show();
                    error = true;
                }
                else {
                    $('.name').hide();
                }

                if ($('#mobile_no').val() == ""){
                    $('.mobile_no').show();
                    error = true;
                }
                else {
                    $('.mobile_no').hide();
                }
                if ($('#station_name').val() == ""){
                    $('.station_name').show();
                    error = true;
                }
                else {
                    $('.station_name').hide();
                }

                if (error == false)
                {
                    $('.addstation').submit();
                }

            });
             $('#mobile_no').keyup(function () {
                $('.mobile_no').hide();
                checkDec(this);
            });
            function checkDec(el){
                var ex = /^[0-9]+\.?[0-9]*$/;
                if(ex.test(el.value)==false){
                    el.value = el.value.substring(0,el.value.length - 1);
                }
            }
             $('#name').keyup(function () {
                $('.name').hide();

            })
             $('#mobile_no').keyup(function () {
                $('.mobile_no').hide();

            })
            $('#station_name').click(function () {
                $('.station_name').hide();

            })
             })
</script>

{% endblock %}

templates/stations/add_stations.html
{% extends 'base.html' %}
{%block menu_station%}active{%endblock%}
{% block submenu_add_station%}active{%endblock%}

{% block content %}
    <div class="col-md-6">
        <br>
        <a href="{% url 'route:list_station' %}"><button type="button" class="btn btn-primary" style="float: left">All Stations</button></a>
        <br><br><br>
        <div class="content-panel">
            <h3 class="text-center">New Stations</h3>
            <div class="panel-body">
                <form action="{% url 'route:add_station' %}" method="post" class="addstation" >
                    {% csrf_token %}
                    <br>
                    <label><strong>Name</strong></label>
                    <input type="text" class="form-control" id="name" name="name">
                    <span class="name" style="color: red; display: none" >This Field is Requried</span><br>
                    <label><strong>Fare</strong></label>
                    <input title="text" class="form-control daewoo_name" id="fare" name="fare">
                    <span class="fare" style="color: red; display: none" >This Field is Requried</span><br>
                    <label><strong>Select Destination</strong></label>
                   <select name="name1" id="destination" class="form-control">
                    <option value="">Destination</option>
                        {% for object in destinations %}
                        <option value="{{ object.name }}">{{ object.name }}</option>
                        {% endfor %}
                   </select>
                    <span class="destination" style="color: red; display: none" >This Field is Requried</span><br>
                <label><strong>Daewoo Type</strong></label>
                    <input type="text" class="form-control" id="daewootype" name="daewoo_type" list="type_list">
                    <datalist id="type_list">
                        <option value="2 X 1"></option>
                        <option value="2 X 2"></option>
                        <option value="HINO"></option>
                    </datalist>
                    <span class="daewootype_error" style="color: red; display: none" >This Field is Requried</span>
                <br>
                <br>
                     <input type="button" id="save" value="Save" class="btn btn-primary right">
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
{{ block.super }}

<script>
 $(document).ready(function(){
 $('#save').on('click', function () {
                var error = false;

                if ($('#name').val() == ""){
                    $('.name').show();
                    error = true;
                }
                else {
                    $('.name').hide();
                }

                if ($('#fare').val() == ""){
                    $('.fare').show();
                    error = true;
                }
                else {
                    $('.fare').hide();
                }
                if ($('#destination').val() == ""){
                    $('.destination').show();
                    error = true;
                }
                else {
                    $('.destination').hide();
                }
                if ($('#daewootype').val() == ""){
                    $('.daewootype_error').show();
                    error = true;
                }
                else {
                    $('.daewootype_error').hide();
                }
                if (error == false)
                {
                    $('.addstation').submit();
                }

            });
             $('#fare').keyup(function () {
                $('.fare').hide();
                checkDec(this);
            });
            function checkDec(el){
                var ex = /^[0-9]+\.?[0-9]*$/;
                if(ex.test(el.value)==false){
                    el.value = el.value.substring(0,el.value.length - 1);
                }
            }
             $('#name').keyup(function () {
                $('.name').hide();

            })
             $('#fare').keyup(function () {
                $('.fare').hide();

            })
            $('#destination').click(function () {
                $('.destination').hide();

            })
             $('#daewootype').click(function () {
                $('.daewootype_error').hide();

            })
             })
</script>

{% endblock %}

templates/stations/list_reservedstations.html
{% extends 'base.html' %}
{%block menu_reserved_stations%}active{%endblock%}
{% block submenu_list_reservation%}active{%endblock%}

{% block content %}

        <div class="row">
            <div class="col-lg-12">
                <br>
                <a href="{% url 'booking:add_reservedstations' %}"><button type="button" class="btn btn-primary">Add Stations Reserved</button></a>
                <br><br>
                <div class="content-panel table-responsive">
                    <h2 class="text-center">Reserved Stations List</h2>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="input-group custom-search-form col-lg-12" style="left: 5px">
                                <input type="text" class="form-control search-daewoo" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>

                    <hr>
                    <table class="table table-striped table-advance table-hover daewoos-table">
                        <thead>
                        <tr>
                            <th>S.No</th>
                            <th><i class="fa fa-bullhorn"></i> Name</th>
                            <th><i class=" fa fa-bookmark"></i> Mobile NO.</th>
                            <th><i class=" fa fa-edit"></i> Station Name</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody class="daewoos-table-body">
                        {% if not stationreservations %}
                            <tr><td colspan="6" class="text-center">Record Not Found</td></tr>
                        {% endif %}
                        {% for stations in stationreservations %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="#">{{ stations.name }}</a></td>
                                <td>{{ stations.mobile_no }}</td>
                                <td>{{ stations.station_name }}</td>
                                <td>
                                    <a href="{% url 'booking:update_reservedstations' pk=stations.id %}"><button class="btn btn-primary btn-xs" title="Update Vehicle"><i class="fa fa-edit"></i></button></a>
                                    <a href="{% url 'booking:delete_reservedstations' pk=stations.id %}"><button class="btn btn-danger btn-xs" title="Delete Vehicle"><i class="fa fa-trash-o"></i></button></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

{% endblock %}

templates/stations/list_stations.html
{% extends 'base.html' %}
{%block menu_station%}active{%endblock%}
{% block submenu_list_station%}active{%endblock%}

{% block content %}

        <div class="row">
            <div class="col-lg-12">
                <br>
                <a href="{% url 'route:add_station' %}"><button type="button" class="btn btn-primary">Add Stations </button></a>
                <br><br>
                <div class="content-panel table-responsive">
                    <h2 class="text-center">Stations</h2>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="input-group custom-search-form col-lg-12" style="left: 5px">
                                <input type="text" class="form-control search-daewoo" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>

                    <hr>
                    <table class="table table-striped table-advance table-hover daewoos-table">
                        <thead>
                        <tr>
                            <th>S.No</th>
                            <th><i class="fa fa-bullhorn"></i> Name </th>
                            <th><i class="fa fa-question-circle"></i> Fare </th>
                            <th><i class="fa fa-bullhorn"></i> Last Station </th>
                            <th><i class="fa fa-bullhorn"></i> Daewoo Type </th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody class="daewoos-table-body">
                        {% if not stations %}
                            <tr><td colspan="6" class="text-center">Record Not Found</td></tr>
                        {% endif %}
                        {% for station in stations %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td><a href="#">{{ station.name }}</a></td>
                                <td class="#">{{ station.fare }} </td>
                                <td>{{ station.destination }}</td>
                                <td>{{ station.daewoo_type }}</td>
                                <td>
                                    <a href="{% url 'route:update_station' pk=station.id %}"><button class="btn btn-primary btn-xs" title="Update "><i class="fa fa-edit"></i></button></a>
                                    <a href="{% url 'route:delete_station' pk=station.id %}"><button class="btn btn-danger btn-xs" title="Delete "><i class="fa fa-trash-o"></i></button></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

{% endblock %}

templates/stations/update_reservedstations.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-6">
        <br>
        <a href="{% url 'booking:list_reservedstations' %}"><button type="button" class="btn btn-primary" style="float: left">All Reserved Stations</button></a>
        <br><br><br>
        <div class="content-panel">
            <h3 class="text-center">New Reserved Stations</h3>
            <div class="panel-body">
                <form action="{% url 'booking:update_reservedstations' pk=object.id %}" method="post" class="addstation" >
                    {% csrf_token %}
                    <br>
                    <label><strong>Name</strong></label>
                    <input type="text" class="form-control" id="name" name="name" value="{{ object.name }}">
                    <span class="name" style="color: red; display: none" >This Field is Requried</span><br>
                    <label><strong>Mobile No</strong></label>
                    <input title="text" class="form-control daewoo_name" id="mobile_no" name="mobile_no" value="{{ object.mobile_no }}">
                    <span class="mobile_no" style="color: red; display: none" >This Field is Requried</span><br>
                    <label><strong>Station</strong></label>
                    <input type="text" class="form-control" id="station_name" name="station_name" value="{{ object.station_name }}">
                    <span class="station_name" style="color: red; display: none" >This Field is Requried</span><br>


                     <input type="button" id="save" value="Save" class="btn btn-primary right">
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
{{ block.super }}

<script>
 $(document).ready(function(){
 $('#save').on('click', function () {
                var error = false;

                if ($('#name').val() == ""){
                    $('.name').show();
                    error = true;
                }
                else {
                    $('.name').hide();
                }

                if ($('#mobile_no').val() == ""){
                    $('.mobile_no').show();
                    error = true;
                }
                else {
                    $('.mobile_no').hide();
                }
                if ($('#station_name').val() == ""){
                    $('.station_name').show();
                    error = true;
                }
                else {
                    $('.station_name').hide();
                }

                if (error == false)
                {
                    $('.addstation').submit();
                }

            });
             $('#mobile_no').keyup(function () {
                $('.mobile_no').hide();
                checkDec(this);
            });
            function checkDec(el){
                var ex = /^[0-9]+\.?[0-9]*$/;
                if(ex.test(el.value)==false){
                    el.value = el.value.substring(0,el.value.length - 1);
                }
            }
             $('#name').keyup(function () {
                $('.name').hide();

            })
             $('#mobile_no').keyup(function () {
                $('.mobile_no').hide();

            })
            $('#station_name').click(function () {
                $('.station_name').hide();

            })
             })
</script>

{% endblock %}

templates/stations/update_stations.html
    {% extends 'base.html' %}

    {% block content %}
        <div class="col-md-6">
            <br>
            <a href="{% url 'route:list_station' %}"><button type="button" class="btn btn-primary" style="float: left">All Stations</button></a>
            <br><br><br>
            <div class="content-panel">
                <h3 class="text-center">{{ object.destination.name }} to ({{ object.destination.route }}) </h3>
                <div class="panel-body">
                    <form action="{% url 'route:update_station' pk=object.id %}" method="post" class="addstation" >
                        {% csrf_token %}
                        <label><strong>Name</strong></label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ object.name }}">
                        <span class="name" style="color: red; display: none" >This Field is Requried</span><br>
                        <br>
                        <label><strong>Fare</strong></label>
                        <input title="text" class="form-control daewoo_name" id="fare" name="fare" value="{{ object.fare}}">
                        <span class="fare" style="color: red; display: none" >This Field is Requried</span>
                        <br>
                        <label><strong>Select Destination</strong></label>
                        <select name="name1" id="destination" class="form-control">
                            <option value="{{ object.destination.name }}">{{ object.destination.name }}</option>
                                {% for destination in destinations %}
                                <option  value="{{ destination.name }}">{{ destination.name }}</option>
                                {% endfor %}
                        </select>
                        <span class="destination" style="color: red; display: none" >This Field is Requried</span>
                    <br>
                    <label><strong>Daewoo Type</strong></label>
                    <input type="text" class="form-control" name="daewoo_type" id="daewootype" value="{{ object.daewoo_type }}" list="type_list">
                    <datalist id="type_list">
                        <option value="2 X 1"></option>
                        <option value="2 X 2"></option>
                        <option value="HINO"></option>
                    </datalist>
                     <span class="daewootype" style="color: red; display: none" >This Field is Requried</span>
                        <br><br>
                         <input type="button" id="save" value="Update" class="btn btn-primary right">
                    </form>
                </div>
            </div>
        </div>
    {% endblock %}
    {% block scripts %}
{{ block.super }}

<script>
 $(document).ready(function(){
 $('#save').on('click', function () {
                var error = false;

                if ($('#name').val() == ""){
                    $('.name').show();
                    error = true;
                }
                else {
                    $('.name').hide();
                }

                if ($('#fare').val() == ""){
                    $('.fare').show();
                    error = true;
                }
                else {
                    $('.fare').hide();
                }
                if ($('#destination').val() == ""){
                    $('.destination').show();
                    error = true;
                }
                else {
                    $('.destination').hide();
                }
                if ($('#daewootype').val() == ""){
                    $('.daewootype_error').show();
                    error = true;
                }
                else {
                    $('.daewootype_error').hide();
                }

                if (error == false)
                {
                    $('.addstation').submit();
                }

            });
             $('#fare').keyup(function () {
                $('.fare').hide();
                checkDec(this);
            });
            function checkDec(el){
                var ex = /^[0-9]+\.?[0-9]*$/;
                if(ex.test(el.value)==false){
                    el.value = el.value.substring(0,el.value.length - 1);
                }
            }
             $('#name').keyup(function () {
                $('.name').hide();
            })
             $('#fare').keyup(function () {
                $('.fare').hide();
            })
            $('#destination').click(function () {
                $('.destination').hide();
            })
            $('#daewootype').click(function () {
                $('.daewootype_error').hide();

            })
             })
</script>

{% endblock %}