common/urls.py
from django.conf.urls import url, include
from common.views import (
    LoginView, LogoutView, HomePageView, RegisterView, UserDeleteView,
    UserProfileList, UserTicketRecordsView,InchargePageView, DailyReportsView,
    MonthlyReportsView
)

urlpatterns = [

    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', HomePageView.as_view(), name='index'),
    url(r'^incharge/$', InchargePageView.as_view(), name='index2'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(
        r'^userlist/$',
        UserProfileList.as_view(),
        name='list_user'
    ),

    url(
        r'^user/delete/(?P<pk>\d+)/$',
        UserDeleteView.as_view(),
        name='delete_user'
    ),

    url(
        r'^user/(?P<user_id>\d+)/record/$',
        UserTicketRecordsView.as_view(),
        name='user_records'
    ),
    url(
        r'^user/(?P<user_id>\d+)/record/(?P<date>[a-zA-Z0-9_-]+)/$',
        UserTicketRecordsView.as_view(),
        name='user_records_date'
    ),
    url(
        r'^daily/reports/$',
        DailyReportsView.as_view(),
        name='daily_reports'
    ),
    url(
        r'^monthly/reports/$',
        MonthlyReportsView.as_view(),
        name='monthly_reports'
    ),
]

daewoo_booking/urls.py
from django.conf.urls import url, include
from daewoo_booking.views import (
    CreateSchedule, SeatBooking,  BookingTicket,
    VehicleBookingDetailsForm, VehicleBookingDetails, StationReservationList, AddStationReservation, DeleteStationReservation,
    TicketCancellationFormView, BookingListView, BookingDeleteView, PassengerRecordView, PassengerRecordListView, UpdateStationReservation,
    VehicleBookingCNICDetails, VehicleBookingCNICDetailsForm,
)

from daewoo_booking.api_views import (
    CreateBookingAPIView, MakeBookingPaymentAPIView
)

urlpatterns = [
    url(
        r'^schedule/$',
        CreateSchedule.as_view(),
        name='create_schedule'
    ),
    url(
        r'^seat/destination/(?P<destination_id>\d+)/'
        r'station/(?P<station_id>\d+)/departure'
        r'/(?P<departure_id>\d+)/date/(?P<date>.+)/$',
        SeatBooking.as_view(),
        name='booking_seat'
    ),
    url(
        r'^(?P<booking_id>\d+)/ticket/$',
        BookingTicket.as_view(),
        name='booking_ticket'
    ),

    url(
        r'^vehicle/details/form/$',
        VehicleBookingDetailsForm.as_view(),
        name='vehicle_details_form'
    ),

    url(
        r'^vehicle/cnic/details/form/$',
        VehicleBookingCNICDetailsForm.as_view(),
        name='vehicle_cnic_details_form'
    ),

    url(
        r'^vehicle/destination/(?P<destination_id>\d+)/'
        r'timing/(?P<timing_id>\d+)/date/(?P<date>.+)/details/',
        VehicleBookingDetails.as_view(),
        name='vehicle_details'
    ),
    url(
        r'^vehicle/cnic/destination/(?P<destination_id>\d+)/'
        r'timing/(?P<timing_id>\d+)/date/(?P<date>.+)/details/',
        VehicleBookingCNICDetails.as_view(),
        name='vehicle_cnic_details'
    ),


    url(
        r'^seat/booking/$',
        SeatBooking.as_view(),
        name='seat_booking'
    ),

    url(
        r'^ticket/cancellation/form/$',
        TicketCancellationFormView.as_view(),
        name='ticket_cancellation_form'
    ),

    url(
        r'^destination/(?P<destination_id>\d+)/'
        r'timing/(?P<timing_id>\d+)/date/(?P<date>.+)/list/',
        BookingListView.as_view(),
        name='booking_list'
    ),

    url(
        r'^(?P<pk>\d+)/delete/$',
        BookingDeleteView.as_view(),
        name='delete_booking'
    ),

    url(
        r'^passenger/record/$',
        PassengerRecordView.as_view(),
        name='passenger_record'
    ),

    url(
        r'^passenger/(?P<code>.+)/record/$',
        PassengerRecordListView.as_view(),
        name='passenger_record_result'
    ),

    # Booking API's
    url(
        r'^create/api/$',
        CreateBookingAPIView.as_view(),
        name='create_booking_api'
    ),

    url(
        r'^reservedstations/$',
        StationReservationList.as_view(),
        name='list_reservedstations'
    ),

    url(
        r'^add/reservedstations/$',
        AddStationReservation.as_view(),
        name='add_reservedstations'
    ),

    url(
        r'^delete/reservedstations/(?P<pk>\d+)/$',
        DeleteStationReservation.as_view(),
        name='delete_reservedstations'
    ),

    url(
        r'^update/reservedstations/(?P<pk>\d+)/$',
        UpdateStationReservation.as_view(),
        name='update_reservedstations'
    ),

    url(
        r'^(?P<booking_id>\d+)/payment/api/$',
        MakeBookingPaymentAPIView.as_view(),
        name='make_payment_api'
    )
]

daewoo_route/urls.py
from django.conf.urls import url, include
from daewoo_route.views import (
    AddRoute, RouteList, RouteUpdateView, RouteDeleteView, DestinationList, DestinationUpdateView, AddDestination,
    DestinationDeleteView, AddStation, StationsList, StationDeleteView, StationUpdateView, AddDepartureTiming,
    DepartureTimingList, DepartureTimingUpdateView, DepartureTimingDeleteView,
)

from daewoo_route.api_views import DepartureTimingAPIView, StationsAPIView

urlpatterns = [
    url(
        r'^add/$',
        AddRoute.as_view(),
        name='add_route'
    ),

    url(
        r'^list/$',
        RouteList.as_view(),
        name='list_route'
    ),

    url(
        r'^delete/(?P<pk>\d+)/$',
        RouteDeleteView.as_view(),
        name='delete_route'
    ),

    url(
        r'^update/(?P<pk>\d+)/$',
        RouteUpdateView.as_view(),
        name='update_route'
    ),

    ############################ Destination URLS ##################################

    url(
        r'^adddestination/$',
        AddDestination.as_view(),
        name='add_destination'
    ),

    url(
        r'^listdestination/$',
        DestinationList.as_view(),
        name='list_destination'
    ),

    url(
        r'^deletedestination/(?P<pk>\d+)/$',
        DestinationDeleteView.as_view(),
        name='delete_destination'
    ),

    url(
        r'^updatedestination/(?P<pk>\d+)/$',
        DestinationUpdateView.as_view(),
        name='update_destination'
    ),

    ###########################  Stations URLS ######################################

    url(
        r'^addstaion/$',
        AddStation.as_view(),
        name='add_station'
    ),

    url(
        r'^liststation/$',
        StationsList.as_view(),
        name='list_station'
    ),

    url(
        r'^deletestation/(?P<pk>\d+)/$',
        StationDeleteView.as_view(),
        name='delete_station'
    ),

    url(
        r'^updatestation/(?P<pk>\d+)/$',
        StationUpdateView.as_view(),
        name='update_station'
    ),

    ######################################## Departure Timing Urls #####################################

    url(
        r'^adddeparture/$',
        AddDepartureTiming.as_view(),
        name='add_departure'
    ),

    url(
        r'^listdeparture/$',
        DepartureTimingList.as_view(),
        name='list_departure'
    ),

    url(
        r'^deletedeparture/(?P<pk>\d+)/$',
        DepartureTimingDeleteView.as_view(),
        name='delete_departure'
    ),

    url(
        r'^updatedeparture/(?P<pk>\d+)/$',
        DepartureTimingUpdateView.as_view(),
        name='update_departure'
    ),

    ########################################  Route Timings URLS #######################################
    url(
        r'^departure/timing/api/$',
        DepartureTimingAPIView.as_view(),
        name='departure_timing_api'
    ),

    url(
        r'^stations/api/$',
        StationsAPIView.as_view(),
        name='stations_api'
    ),
]

daewoo_staff/urls.py
from django.conf.urls import url, include
from daewoo_staff.views import (
    AddDriver, DriverList, DriverDeleteView, DriverUpdateView, AddEmployee, EmployeeList, EmployeeDeleteView, EmployeeUpdateView,

)

urlpatterns = [
    url(
        r'^add/$',
        AddDriver.as_view(),
        name='add_driver'
    ),

    url(
        r'^list/$',
        DriverList.as_view(),
        name='driver_list'
    ),

    url(
        r'^delete/(?P<pk>\d+)/$',
        DriverDeleteView.as_view(),
        name='driver_delete'
    ),

    url(
        r'^update/(?P<pk>\d+)/$',
        DriverUpdateView.as_view(),
        name='driver_update'
    ),
########################################## Employee YRLS ###################################
    url(
        r'^addemployee/$',
        AddEmployee.as_view(),
        name='add_employee'
    ),

    url(
        r'^listemployee/$',
        EmployeeList.as_view(),
        name='list_employee'
    ),

    url(
        r'^deleteemployee/(?P<pk>\d+)/$',
        EmployeeDeleteView.as_view(),
        name='delete_employee'
    ),

    url(
        r'^updateemployee/(?P<pk>\d+)/$',
        EmployeeUpdateView.as_view(),
        name='update_employee'
    ),
]

daewoo_ticketing_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('common.urls', namespace='common')),
    url(r'^booking/', include('daewoo_booking.urls', namespace='booking')),
    url(r'^vehicle/', include('daewoo_vehicle.urls', namespace='vehicle')),
    url(r'^staff/', include('daewoo_staff.urls', namespace='staff')),
    url(r'^route/', include('daewoo_route.urls', namespace='route')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

daewoo_vehicle/urls.py
from django.conf.urls import url, include
from daewoo_vehicle.views import AddDaewoo
from daewoo_vehicle.views import VehicleList
from daewoo_vehicle.views import VehicleDeleteView
from daewoo_vehicle.views import VehicleUpdateView
urlpatterns = [
    url(
        r'^add/$',
        AddDaewoo.as_view(),
        name='add_daewoo'
    ),

    url(
        r'^list/$',
        VehicleList.as_view(),
        name='vehicle_list'
    ),

    url(
        r'^delete/(?P<pk>\d+)/$',
        VehicleDeleteView.as_view(),
        name='vehicle_delete'
    ),

    url(
        r'^update/(?P<pk>\d+)/$',
        VehicleUpdateView.as_view(),
        name='vehicle_update'
    )

]

templates/index.html
{% extends 'base.html' %}
{% block menu_dashbaord %}active{% endblock %}

{% block content %}
<body>
<section id="container" >
    <br><br>
    <div class="row">
        <div class="col-lg-4 col-md-6">
            <a href="#">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-12 text-center">
                                <i class="fa fa-bar-chart-o fa-5x"></i>
                            </div>
                            <div class="col-xs-12 text-center">
                                <div class="huge">Reports</div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-4 col-md-6">
            <a href="{% url 'vehicle:vehicle_list' %}">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-12 text-center">
                                <i class="fa  fa-th-large fa-5x"></i>
                            </div>
                            <div class="col-xs-12 text-center">
                                <div class="huge">Vehicles</div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-4 col-md-6">
            <a href="{% url 'route:list_route' %}">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-12 text-center">
                                <i class="fa fa-list-ul fa-5x"></i>
                            </div>
                            <div class="col-xs-12 text-center">
                                <div class="huge">Route</div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-4 col-md-6">
            <a href="{% url 'route:list_destination' %}">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-12 text-center">
                                <i class="fa fa-road fa-5x"></i>
                            </div>
                            <div class="col-xs-12 text-center">
                                <div class="huge">Destination</div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-4 col-md-6">
            <a href="{% url 'booking:vehicle_details_form' %}">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-12 text-center">
                                <i class="fa fa-edit fa-5x"></i>
                            </div>
                            <div class="col-xs-12 text-center">
                                <div class="huge">Booking Deatails</div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-4 col-md-6">
            <a href="{% url 'route:list_departure' %}">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-12 text-center">
                                <i class="fa fa-file-text-o fa-5x"></i>
                            </div>
                            <div class="col-xs-12 text-center">
                                <div class="huge">Departure Time</div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-4 col-md-6">
            <a href="{% url 'route:list_station' %}">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-12 text-center">
                                <i class="fa  fa-dropbox fa-5x"></i>
                            </div>
                            <div class="col-xs-12 text-center">
                                <div class="huge">Stations</div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer ">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-4 col-md-6">
            <a href="{% url 'staff:driver_list' %}">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-12 text-center">
                                <i class="fa  fa-male fa-5x"></i>
                            </div>
                            <div class="col-xs-12 text-center">
                                <div class="huge">Drivers</div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer ">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-4 col-md-6">
            <a href="{% url 'staff:list_employee' %}">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-12 text-center">
                                <i class="fa  fa-group fa-5x"></i>
                            </div>
                            <div class="col-xs-12 text-center">
                                <div class="huge">Employees</div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer ">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </a>
        </div>
    </div>
</section>
</body>
{% endblock %}

{#{% block scripts %}#}
{#    {{ block.super }}#}
{#    <script>#}
{#    $('section#container').addClass('sidebar-closed');#}
{#    </script>#}
{##}
{#{% endblock %}#}

templates/index2.html
{% extends 'base.html' %}
{% block menu_reports %}active{% endblock %}

{% block content %}


{% endblock %}

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
{#    <meta name="author" content="Dashboard">#}
{#    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">#}

    <title>Ticketing System | Partum Solutions | Business Software Solution Providers</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet">
    <style>
        .errorlist{
            display: inline-block;
            color: red;
            font-size: smaller;
            float: right;
        }
        .error-alert{
            text-align: center;
            padding-bottom: 10px;
            font-size: xx-large;
            color: red;
        }
    </style>
</head>

<body>
<div id="login-page">
    <div class="container">
        <form class="form-login" method="post" action="{% url 'common:login' %}">
            <h2 class="form-login-heading">sign in now</h2>
            <div class="login-wrap">
                {% if form.errors or form.non_field_errors %}
                    <div class="error-alert">
                        <i class="fa fa-warning pull-center"></i>
                    </div>
                {% endif %}
                {% csrf_token %}
                {% if form.non_field_errors %}
                    <div>
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
                <input type="text" class="form-control" placeholder="Username" name="username" autofocus>
                {% if form.errors %}
                    {{ form.errors.username }}
                {% endif %}
                <br>
                <input type="password" class="form-control" name="password" placeholder="Password">
                {% if form.errors %}
                    {{ form.errors.password  }}
                {% endif %}
{#                <label class="checkbox">#}
{#                    <span class="pull-right">#}
{#                        <a data-toggle="modal" href="login.html#myModal"> Forgot Password?</a>#}
{#                    </span>#}
{#                </label>#}
                {% if not config.demo %}
                    <label class="checkbox">
                        <span class="pull-right">
                           Not registered? <a data-toggle="modal" href="#"> Join now</a>
                        </span>
                    </label>
                {% else %}
                    <br>
                {% endif %}

                <button class="btn btn-primary btn-block" type="submit"><i class="fa fa-lock"></i> SIGN IN</button>
            </div>
{#            <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade">#}
{#                <div class="modal-dialog">#}
{#                    <div class="modal-content">#}
{#                        <div class="modal-header">#}
{#                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>#}
{#                            <h4 class="modal-title">Forgot Password ?</h4>#}
{#                        </div>#}
{#                        <div class="modal-body">#}
{#                            <p>Enter your e-mail address below to reset your password.</p>#}
{#                            <input type="text" name="email" placeholder="Email" autocomplete="off" class="form-control placeholder-no-fix">#}
{##}
{#                        </div>#}
{#                        <div class="modal-footer">#}
{#                            <button data-dismiss="modal" class="btn btn-default" type="button">Cancel</button>#}
{#                            <button class="btn btn-primary" type="button">Submit</button>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
            {% if config.demo %}
                <hr>
                <table class="table table-striped table-advance table-hover table-bordered">
                    <h3 style="text-align: center">Test Accounts</h3>
                    <thead>
                        <tr>
                            <th>User Type</th>
                            <th>Username</th>
                            <th>Password</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Owner</td>
                            <td>demo</td>
                            <td>Dairy000</td>
                        </tr>
                    </tbody>
                </table>
                <br>
            {% endif %}
        </form>
    </div>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

templates/new_user.html
{% extends 'base.html' %}
{% block menu_users %}active{% endblock %}
{% block submenu_new_user %}active{% endblock %}

{% block content %}

    <div class="col-md-6">
        <br>
        <a href="{% url 'common:list_user' %}"><button type="button" class="btn btn-primary" style="float: left">All Users</button></a>
        <br><br><br>
        <div class="content-panel">
            <h3 class="text-center">New User</h3>
            <div class="panel-body">
                <form action="{% url 'common:register' %}" method="post" class="newdaewoo" >
                    {% csrf_token %}

                    <label><strong>Username</strong></label>
                    <input type="text" class="form-control username" id="username" name="username"><br>

                    <label><strong>Password</strong></label>
                    <input type="text" class="form-control password1" id="password1" name="password1"><br>

                    <label><strong>Confirm Password</strong></label>
                    <input type="text" class="form-control password2" id="password2" name="password2"><br>

                    <label><strong>User Type</strong></label>
                    <select class="form-control user_type" id="user_type" name="user_type">
                        <option>Munshi</option>
                        <option>Manager</option>
                        <option>Incharge</option>
                    </select><br>

                    <label><strong>Route</strong></label>
                    <select class="form-control route" id="route" name="route_name">
                        {% for route in routes %}
                            <option>{{ route.name }}</option>
                        {% endfor %}
                    </select><br>
                    <input type="submit" id="save" value="Save User" class="btn btn-primary" style="float: right;">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/user_profiles.html
{% extends 'base.html' %}
{%block menu_users%}active{%endblock%}
{% block submenu_user_list%}active{%endblock%}
{% block content %}

        <div class="row">
            <div class="col-lg-12">
                <br>
                {% if request.user.user_profile.user_type == request.user.user_profile.USER_TYPE_MANAGER %}
                <a href="{% url 'common:register' %}"><button type="button" class="btn btn-primary">New User</button></a>
                {% endif %}
                <br><br>
                <div class="content-panel table-responsive">
                    <h2 class="text-center">Users Accounts</h2>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="input-group custom-search-form col-lg-12" style="left: 5px">
                                <input type="text" class="form-control search-daewoo" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>

                    <hr>
                    <table class="table table-striped table-advance table-hover daewoos-table">
                        <thead>
                        <tr>
                            <th>S.No</th>
                            <th><i class="fa fa-question-circle"></i> Username </th>
                            <th><i class=" fa fa-bookmark"></i> User Type</th>
                            <th><i class=" fa fa-bookmark"></i> Route</th>
                            <th><i class=" fa fa-edit"></i> Total Amount</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody class="daewoos-table-body">
                        {% if not users %}
                            <tr><td colspan="6" class="text-center">Record Not Found</td></tr>
                        {% endif %}
                        {% for account in users %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ account.user }}</td>
                                <td>{{ account.user_type }}</td>
                                <td>{{ account.user.user_route.route|title }}</td>
                                <td>{{ account.munshi_records_total|floatformat:'-2' }} </td>
                                <td>
                                {% if request.user.user_profile.user_type == request.user.user_profile.USER_TYPE_MANAGER %}
                                    <a href="{% url 'common:delete_user' pk=account.user.id %}"><button onclick="return confirm('Are you sure you want to DELETE USER?')" class="btn btn-danger btn-xs" title="Delete "><i class="fa fa-trash-o"></i></button></a>
                                    {% endif %}
                                {% if account.user_type == 'Munshi' %}
                                    <a href="{% url 'common:user_records' user_id=account.user.id %}"><button class="btn btn-success btn-xs" title="Details "><i class="fa fa-eye"></i></button></a>
                                {% endif %}

                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

{% endblock %}